/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/menu-management`; params?: Router.UnknownInputParams; } | { pathname: `/orders`; params?: Router.UnknownInputParams; } | { pathname: `/select-table`; params?: Router.UnknownInputParams; } | { pathname: `/select-takeaway`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/orders`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/takeaway`; params?: Router.UnknownInputParams; } | { pathname: `/utils/mockData`; params?: Router.UnknownInputParams; } | { pathname: `/utils/orderStore`; params?: Router.UnknownInputParams; } | { pathname: `/utils/orderUtils`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/order/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/dine-in/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/takeaway/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/menu-management`; params?: Router.UnknownOutputParams; } | { pathname: `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/select-table`; params?: Router.UnknownOutputParams; } | { pathname: `/select-takeaway`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/takeaway`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/mockData`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/orderStore`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/orderUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/order/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order/dine-in/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order/takeaway/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order-view/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/menu-management${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `/select-table${`?${string}` | `#${string}` | ''}` | `/select-takeaway${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs/orders${`?${string}` | `#${string}` | ''}` | `/tabs/settings${`?${string}` | `#${string}` | ''}` | `/tabs/takeaway${`?${string}` | `#${string}` | ''}` | `/utils/mockData${`?${string}` | `#${string}` | ''}` | `/utils/orderStore${`?${string}` | `#${string}` | ''}` | `/utils/orderUtils${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/menu-management`; params?: Router.UnknownInputParams; } | { pathname: `/orders`; params?: Router.UnknownInputParams; } | { pathname: `/select-table`; params?: Router.UnknownInputParams; } | { pathname: `/select-takeaway`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/orders`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/takeaway`; params?: Router.UnknownInputParams; } | { pathname: `/utils/mockData`; params?: Router.UnknownInputParams; } | { pathname: `/utils/orderStore`; params?: Router.UnknownInputParams; } | { pathname: `/utils/orderUtils`; params?: Router.UnknownInputParams; } | `/+not-found` | `/order/${Router.SingleRoutePart<T>}` | `/order/dine-in/${Router.SingleRoutePart<T>}` | `/order/edit/${Router.SingleRoutePart<T>}` | `/order/takeaway/${Router.SingleRoutePart<T>}` | `/order-view/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/order/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/dine-in/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/takeaway/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
